"""empty message

Revision ID: 258767d818b0
Revises: 423acc1ce579
Create Date: 2021-08-02 04:17:02.842217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '258767d818b0'
down_revision = '423acc1ce579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_new',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('color', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('color_new')
    # ### end Alembic commands ###
