"""empty message

Revision ID: 5bd5241354e4
Revises: d945a4e88746
Create Date: 2021-07-31 14:48:01.685372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd5241354e4'
down_revision = 'd945a4e88746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color')
    # ### end Alembic commands ###
