"""empty message

Revision ID: 423acc1ce579
Revises: 5fd9a51989ca
Create Date: 2021-08-02 03:45:10.171455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423acc1ce579'
down_revision = '5fd9a51989ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('color', 'id')
    # ### end Alembic commands ###
