"""empty message

Revision ID: 5fd9a51989ca
Revises: 5bd5241354e4
Create Date: 2021-07-31 15:49:32.589235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fd9a51989ca'
down_revision = '5bd5241354e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('color', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
